options:
  merge-default-rules: false
  formatter: html
  output-file: 'sass-lint.html'
  max-warnings: 50
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoints
        - mqasd

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notations:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - margin
        - content
